# Generated by Django 3.1.6 on 2021-02-10 14:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_control', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_subproducts',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.product'),
        ),
        migrations.AlterField(
            model_name='product_subproducts',
            name='subproductid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.subproduct'),
        ),
        migrations.AlterField(
            model_name='product_supplies',
            name='productid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.product'),
        ),
        migrations.AlterField(
            model_name='product_supplies',
            name='supplyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.supply'),
        ),
        migrations.AlterField(
            model_name='subproduct_supplies',
            name='subproductid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.subproduct'),
        ),
        migrations.AlterField(
            model_name='subproduct_supplies',
            name='supplyid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='supplies_control.supply'),
        ),
    ]
