# Generated by Django 3.1.6 on 2021-02-18 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplies_control', '0002_auto_20210210_1100'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='production_cost',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='selling_price',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product_subproducts',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product_supplies',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='production_cost',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='recipe_final_weight',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subproduct',
            name='stock',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='subproduct_supplies',
            name='quantity',
            field=models.DecimalField(decimal_places=4, default=None, max_digits=10, null=True),
        )
    ]
